# env
# env: button-press-v2-goal-hidden
# env: drawer-open-v2-goal-hidden
# env: peg-insert-side-v2-goal-hidden
env: peg-insert-side-hard-v2-goal-hidden
# env: handle-press-side-v2-goal-hidden
# env: peg-unplug-side-v2-goal-hidden
# env: assembly-v2-goal-hidden

view: both
run_dir: ./logs/drq-v2-peg-insert-hard-learned_switching-seed1/
random_init_obj_pos: true
seed: 1

add_img_repr_loss: false # whether to have L2 loss b/t view 1 and view 3 representations
img_repr_loss_weight: 1e6 # weight on L2 loss b/t view 1 and view 3 representations

use_vib: false # whether to use variational information bottleneck to regularize the view 3 representation
vib_kl_weight: 1e0

# If resuming training from snapshot (aka checkpoint), you must also change num_train_frames and num_seed_frames
# farther below. In particular, you should change num_seed_frames to be <snapshot_frame_number> + 4000.
resume_training_from_snapshot: false
snapshot_path: /iris/u/moojink/metaworld/logs/drq-v2-peg-insert-both-views-L2-weight1e2-seed1/0/snapshot_990000.pt

# metaworld stuff
proprio_obs_shape: 39
# task settings
image_size: 84
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_train_frames: 1200000
num_seed_frames: 4000
save_train_video_every_frames: 10000
# eval
eval_every_frames: 10000
num_eval_episodes: 20
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
device: cuda
save_video: true
save_train_video: true
use_tb: true
# experiment
experiment: exp

agent:
  _target_: meta_drqv2.DrQV2Agent
  view: ${view}
  img_obs_shape: ??? # to be specified later
  proprio_obs_shape: 117 # 39 * frame_stack(3) = 117
  action_shape: ??? # to be specified later
  device: ${device}
  lr: 1e-4
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: 50
  stddev_schedule: 'linear(1.0,0.1,500000)'
  stddev_clip: 0.3
  add_img_repr_loss: ${add_img_repr_loss}
  img_repr_loss_weight: ${img_repr_loss_weight}
  use_vib: ${use_vib}
  vib_kl_weight: ${vib_kl_weight}

hydra:
  run:
    dir: ${run_dir}