# env
# env: button-press-v2-goal-hidden
# env: drawer-open-v2-goal-hidden
env: peg-insert-side-v2-goal-hidden
# env: handle-press-side-v2-goal-hidden
# env: peg-unplug-side-v2-goal-hidden

view: 1
run_dir: ./logs/delete/
random_init_obj_pos: true
seed: 1

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_train_frames: 1000000
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
device: cuda
save_video: true
save_train_video: false
use_tb: false
# experiment
experiment: exp

agent:
  _target_: drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: 1e-4
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: 50
  stddev_schedule: 'linear(1.0,0.1,500000)'
  stddev_clip: 0.3

hydra:
  run:
    dir: ${run_dir}